baseURL = 'https://cgnomads.github.io'
languageCode = 'en-us'
title = 'CG Nomads'
theme = 'ananke'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true